working integration test

diff --git a/tests/templates/kuttl/opa/41-access-hbase.yaml.j2 b/tests/templates/kuttl/opa/41-access-hbase.yaml.j2
--- a/tests/templates/kuttl/opa/41-access-hbase.yaml.j2
+++ b/tests/templates/kuttl/opa/41-access-hbase.yaml.j2
@@ -64,7 +64,7 @@ commands:
                       annotations:
                         secrets.stackable.tech/class: kerberos-$NAMESPACE
                         secrets.stackable.tech/scope: service=access-hbase
-                        secrets.stackable.tech/kerberos.service.names: testuser
+                        secrets.stackable.tech/kerberos.service.names: admin,developer,public,readonlyuser
                     spec:
                       storageClassName: secrets.stackable.tech
                       accessModes:
@@ -87,31 +87,110 @@ data:
   script.sh: |
     set -ex
     klist -k /stackable/kerberos/keytab
-    kinit -kt /stackable/kerberos/keytab testuser/access-hbase.$NAMESPACE.svc.cluster.local
-    klist
 
     export KERBEROS_REALM=$(grep -oP 'default_realm = \K.*' /stackable/kerberos/krb5.conf)
     cat /stackable/conf/hbase_mount/hbase-site.xml | sed -e 's/${env.KERBEROS_REALM}/'"$KERBEROS_REALM/g" > /stackable/conf/hbase/hbase-site.xml
     cat /stackable/conf/hdfs_mount/core-site.xml | sed -e 's/${env.KERBEROS_REALM}/'"$KERBEROS_REALM/g" > /stackable/conf/hbase/core-site.xml
     cat /stackable/conf/hdfs_mount/hdfs-site.xml | sed -e 's/${env.KERBEROS_REALM}/'"$KERBEROS_REALM/g" > /stackable/conf/hbase/hdfs-site.xml
 
-    cat > /tmp/hbase-script << 'EOF'
-    disable 'test';
-    drop 'test';
+    kdestroy; kinit -kt /stackable/kerberos/keytab admin/access-hbase.$NAMESPACE.svc.cluster.local; klist
 
-    create 'test', 'cf1';
-    put 'test', 'row1', 'cf1', 42;
-    put 'test', 'row2', 'cf1', 43;
-    put 'test', 'row3', 'cf1', 44;
-    scan 'test';
-    count 'test';
+    cat > /tmp/admin-hbase-script << 'EOF1'
+    create_namespace "developers";
+    create_namespace "public";
     exit;
-    EOF
+    EOF1
 
-    if bin/hbase shell /tmp/hbase-script | tee /dev/stderr | grep -q '=> 3'; then
+    cat > /tmp/dev-hbase-script << 'EOF2'
+    create 'developers:test', 'cf1';
+    put 'developers:test', 'row1', 'cf1', 41;
+    put 'developers:test', 'row2', 'cf1', 42;
+    put 'developers:test', 'row3', 'cf1', 43;
+    scan 'developers:test';
+    count 'developers:test';
+    exit;
+    EOF2
+
+    cat > /tmp/public-hbase-script << 'EOF3'
+    create 'public:test', 'cf1';
+    put 'public:test', 'row1', 'cf1', 44;
+    put 'public:test', 'row2', 'cf1', 45;
+    put 'public:test', 'row3', 'cf1', 46;
+    scan 'public:test';
+    count 'public:test';
+    exit;
+    EOF3
+
+    cat > /tmp/readonly-hbase-script << 'EOF4'
+    count 'developers:test';
+    count 'public:test';
+    exit;
+    EOF4
+
+    #------------------------------------------
+    # Admin should be able to create namespaces
+    #------------------------------------------
+    kdestroy; kinit -kt /stackable/kerberos/keytab admin/access-hbase.$NAMESPACE.svc.cluster.local; klist
+
+    expected=$(bin/hbase shell /tmp/admin-hbase-script | grep 'Took ' | wc -l)
+    if [ $expected == 2 ]; then
       echo "Test passed"
-      exit 0
+      #exit 0
     else
       echo "Test failed"
-      exit 1
+      #exit 1
+    fi
+
+    #-------------------------------------------------
+    # Developer should be able to access own namespace
+    #-------------------------------------------------
+    kdestroy; kinit -kt /stackable/kerberos/keytab developer/access-hbase.$NAMESPACE.svc.cluster.local; klist
+
+    expected=$(bin/hbase shell /tmp/dev-hbase-script | grep '=> 3' | wc -l)
+    if [ $expected == 1 ]; then
+      echo "Test passed"
+      #exit 0
+    else
+      echo "Test failed"
+      #exit 1
+    fi
+
+    #------------------
+    # ...but not others
+    #------------------
+    expected=$(bin/hbase shell /tmp/public-hbase-script | grep '=> 3' | wc -l)
+    if [ $expected == 0 ]; then
+      echo "Test passed"
+      #exit 0
+    else
+      echo "Test failed"
+      #exit 1
+    fi
+
+    #----------------------------------------------
+    # Public should be able to access own namespace
+    #----------------------------------------------
+    kdestroy; kinit -kt /stackable/kerberos/keytab public/access-hbase.$NAMESPACE.svc.cluster.local; klist
+
+    expected=$(bin/hbase shell /tmp/public-hbase-script | grep '=> 3' | wc -l)
+    if [ $expected == 1 ]; then
+      echo "Test passed"
+      #exit 0
+    else
+      echo "Test failed"
+      #exit 1
+    fi
+
+    #--------------------------------------------------------
+    # Readyonlyuser should be able to read across namespaces
+    #--------------------------------------------------------
+    kdestroy; kinit -kt /stackable/kerberos/keytab readonlyuser/access-hbase.$NAMESPACE.svc.cluster.local; klist
+
+    expected=$(bin/hbase shell /tmp/readonly-hbase-script | grep '=> 3' | wc -l)
+    if [ $expected == 2 ]; then
+      echo "Test passed"
+      #exit 0
+    else
+      echo "Test failed"
+      #exit 1
     fi
